project:
  type: website
  output-dir: .

website:
  title: "Neuralyzer" # Title of the website
 # favicon:
  navbar:
    collapse-below: lg
    pinned: true
    right:
      - id: intro
        text: "Introduction"
        href: index.qmd
        
      - text: "Tutorials"
        menu:
          - text: "Keypoint Labeling"
            href: examples/keypoint_labeling.qmd
            
      - text: "How-to guides"
        menu:
          - text: "Label Creation"
            href: labeling/keypoint.qmd
          - text: "Mask Creation"
            href: labeling/mask.qmd
            
      - text: "Reference Guides"
        menu:
          - text: "Image Processing"
          - text: "Contrast"
            href: image_processing/contrast.qmd
          - text: "Sharpening"
            href: image_processing/sharpening.qmd
          - text: "CLAHE"
            href: image_processing/clahe.qmd
          - text: "Bilateral Filter"
            href: image_processing/bilateral_filter.qmd
            
          - text: "Behavior Modules"
          - text: "Whisker"
            href: behaviors/whisker.qmd
          - text: "Tongue"
            href: behaviors/tongue.qmd
                
      - text: "Concepts"
        menu:
          - text: "Developer Documentation"
            href: developer/index.qmd
            
  sidebar:
    title: "Developer Documentation"
    style: "docked"
    contents:
      - developer/index.qmd
      - developer/data_manager.qmd 
      - developer/image_processing.qmd

format:
  html:
    theme: github-dark
    smooth-scroll: true
    css: styles.css
    toc: true

editor: visual

