project:
  type: website
  output-dir: .

website:
  title: "Neuralyzer" # Title of the website
 # favicon:
  navbar:
    collapse-below: lg
    pinned: true
    right:
      - id: intro
        text: "Introduction"
        href: index.qmd
        
      - text: "Tutorials"
        menu:
          - text: "Keypoint Labeling"
            href: examples/keypoint_labeling.qmd
            
      - text: "How-to guides"
        menu:
          - text: "Label Creation"
            href: labeling/keypoint.qmd
          - text: "Mask Creation"
            href: labeling/mask.qmd
            
      - text: "Reference Guides"
        menu:
          - text: "User Guide"
            href: user_guide/index.qmd
          - text: "Developer Guide"
            href: developer/index.qmd
                
      - text: "Concepts"
            
  sidebar:
    - title: "Developer Documentation"
      style: "docked"
      contents:
        - developer/index.qmd
        - developer/contributing_code.qmd
        - developer/data_manager.qmd 
        - developer/image_processing.qmd

    - title: "User Guide"
      style: "docked"
      contents:
        - user_guide/index.qmd
        - user_guide/JSON_loading.qmd
        - user_guide/image_processing/contrast.qmd
        - user_guide/image_processing/sharpening.qmd
        - user_guide/image_processing/clahe.qmd
        - user_guide/image_processing/bilateral_filter.qmd
        - user_guide/behaviors/whisker.qmd
        - user_guide/behaviors/tongue.qmd


format:
  html:
    theme: github-dark
    smooth-scroll: true
    css: styles.css
    toc: true

editor: visual

