project:
  type: website
  output-dir: .

website:
  title: "Behavior Toolbox"
  sidebar:
    style: docked
    contents:
      - section: "Introduction"
        contents: 
        - index.qmd
        
      - section: "Tutorials"
        contents: 
        - examples/keypoint_labeling.qmd
        
      - section: "How-to guides"
        contents:
          - section: "Label Creation"
            contents:
              - labeling/keypoint.qmd
              - labeling/mask.qmd
              
      - section: "Reference Guides"
        contents:
        
          - section: "Image Processing"
            contents:
              - image_processing/contrast.qmd
              - image_processing/sharpening.qmd
              - image_processing/clahe.qmd
              - image_processing/bilateral_filter.qmd
      
          - section: "Behavior Modules"
            contents:
              - behaviors/whisker.qmd
              - behaviors/tongue.qmd
              
      - section: "Concepts"
        contents:
        
          - section: "Developer"
            contents: 
              - developer/data_manager.qmd
              - developer/image_processing.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

