project:
  type: website
  output-dir: .

website:
  title: "Behavior Toolbox"
  sidebar:
    style: docked
    contents:
      - section: "Introduction"
        contents: 
        - index.qmd
        
      - section: "Example Uses"
        contents:
        - examples/keypoint_labeling.qmd
        
      - section: "Developer"
        contents: 
        - developer/data_manager.qmd
        - developer/image_processing.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

